In [6]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])# 每个数据类型一样，大小不可更改
print(arr)
arr.dtype
#arr.ndim
#arr.shape
#arr.size    #   元素总数

[[1 2 3]
 [4 5 6]
 [7 8 9]]


dtype('int32')

In [31]:
# np.arange(1,100,2,float,like=None)
array_1=np.linspace(0,100,num=50,endpoint=True,retstep=False,dtype=int,axis=0)

In [36]:
arr[-1]

array([7, 8, 9])

In [35]:
array_1[-1]

100

In [37]:
indices =[0,0]

In [16]:
array_3=np.arange(25).reshape(5,5)
array_3[2:4,3:5]=0
print(array_3)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12  0  0]
 [15 16 17  0  0]
 [20 21 22 23 24]]


In [17]:
a=np.arange(10).reshape(2,5)
b=np.arange(10,20).reshape(2,5)
c=np.concatenate((a,b),axis=0)
print(c)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [27]:
a=np.arange(27).reshape(3,3,3)
# a[...,1]
a[[0,0,0]]
a[:]=0
a

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [31]:
b=np.array([1,2,3])
# print(b)
c=a*b
print(c)
d=np.fmin(a,b)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
